#source : https://github.com/turbinesFoam/turbinesFoam
sudo: required
python:
  - "3.7"
dist: xenial
language: cpp

env:
  - OF_VERS=6

before_install:
    - sudo python3 -V
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install --upgrade pip
    - sudo pip3 install -U setuptools
    - sudo pip3 install fluidfoam
    - sudo add-apt-repository http://dl.openfoam.org/ubuntu
    - sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
    - sudo apt-get update -qq
    - sudo apt-get install -qq openfoam${OF_VERS}
    - sudo apt-get install -qq vera++

install:
    - ./foamStyleCheck/checkStyle
    - sudo chown -R $USER /opt/openfoam${OF_VERS}/platforms
    - source /opt/openfoam${OF_VERS}/etc/bashrc
    - ./Allwmake

before_script:
    - source /opt/openfoam${OF_VERS}/etc/bashrc

script:
    - cd test-ci/1DBedLoad && ./Allrun
    - cd ../1DSedim && ./Allrun
    - python3 test_Sedimentation.py 

notifications:
  slack:
    rooms:
      sedfoam:gFgw4hb2TY4uMX10tUA0xb4F#dev
    on_success: always
