version: 2

jobs:
  build:

    docker:
      - image: ubuntu:focal

    environment:
      WM_NCOMPPROCS: 2
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive

    working_directory: /root/sedfoam

    steps:
      - run:
          name: Install package dependencies
          command: apt-get update && apt-get install -y build-essential cmake openmpi-bin libopenmpi-dev python-dev git bc
          
      - run:
          name: Make project and user dir
          command: mkdir -p /root/sedfoam

      - checkout:
          path: /root/sedfoam

      - run:
          name: Add OpenFOAM package repository
          command: apt-get install -y software-properties-common wget apt-transport-https && sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -" && add-apt-repository http://dl.openfoam.org/ubuntu

      - run:
          name: Install OpenFOAM 7
          command: apt-get update && apt-get -y install openfoam7 vera++

      - run:
          name: pull checkStyle submodule
          command: >
            shopt -s expand_aliases &&
            git submodule init &&
            git submodule update --remote

      - run:
          name: Check style
          command: >
            shopt -s expand_aliases &&
            ./foamStyleCheck/checkStyle

      - run:
          name: Build sedFoam
          command: >
            shopt -s expand_aliases &&
            source /opt/openfoam7/etc/bashrc &&
            ./Allwmake
          no_output_timeout: 30m

  test:
    docker:
      - image: ubuntu:focal

    working_directory: /root/sedfoam

    steps:
      - run:
          name: Install python3 packages
          command: >
            shopt -s expand_aliases &&
            apt-get update && apt-get install -y python3-pip && 
            pip3 install fluidfoam

      - run:
          name: First sedfoam test
          command: >
            shopt -s expand_aliases &&
            source /opt/openfoam7/etc/bashrc &&
            cd test-ci/1DSedim && cp -f constant/forceProperties.sedim constant/forceProperties &&
            cp -f system/controlDict.sedim system/controlDict && ./Allrun &&
            python3 test_Sedimentation.py

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
