version: 2

jobs:
  checkstyle:
    docker:
      - image: ubuntu:focal 

    environment:
      WM_NCOMPPROCS: 2
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive

    working_directory: /root/sedfoam
    steps:
      - run:
          name: Make project and user dir
          command: mkdir -p /root/sedfoam

      - checkout:
          path: /root/sedfoam

      - run:
          name: Install vera++
          command: apt-get update && apt-get install -y git vera++

      - run:
          name: pull checkStyle submodule
          command: >
            shopt -s expand_aliases &&
            git submodule init &&
            git submodule update --remote

      - run:
          name: Check style
          command: >
            shopt -s expand_aliases &&
            ./foamStyleCheck/checkStyle


  build:

    docker:
      - image: openfoamplus/of_v2006_centos73 

    environment:
      WM_NCOMPPROCS: 2
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive

    working_directory: /root/sedfoam

    steps:
      - run:
          name: Make project and user dir
          command: mkdir -p /root/sedfoam

      - checkout:
          path: /root/sedfoam

      - run:
          name: Build sedFoam
          command: >
            shopt -s expand_aliases &&
            source /opt/OpenFOAM/setImage_v2006.sh &&
            ./Allwmake
      - persist_to_workspace:
          root: /root
          paths: OpenFOAM

  test1:
    docker:
      - image: openfoamplus/of_v2006_centos73 

    working_directory: /root/sedfoam

    steps:
      - checkout:
          path: /root/sedfoam
      - attach_workspace:
          at: /root
      - run:
          name: Install python3 packages
          command: >
            shopt -s expand_aliases &&
            apt-get update && apt-get install -y python3-pip && 
            pip3 install fluidfoam

      - run:
          name: First sedfoam test
          command: >
            shopt -s expand_aliases &&
            source /opt/openfoam7/etc/bashrc &&
            cd test-ci/1DSedim && cp -f constant/forceProperties.sedim constant/forceProperties &&
            cp -f system/controlDict.sedim system/controlDict && ./Allrun &&
            python3 test_Sedimentation.py
          no_output_timeout: 30m

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkstyle
      - build
      - test1:
          requires:
            - build
