version: 2

jobs:
  checkstyle:
    docker:
      - image: ubuntu:focal 

    environment:
      WM_NCOMPPROCS: 2
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive

    working_directory: /root/sedfoam
    steps:
      - run:
          name: Make project and user dir
          command: mkdir -p /root/sedfoam

      - checkout:
          path: /root/sedfoam

      - run:
          name: Install vera++
          command: apt-get update && apt-get install -y git vera++

      - run:
          name: pull checkStyle submodule
          command: >
            shopt -s expand_aliases &&
            git submodule init &&
            git submodule update --remote

      - run:
          name: Check style
          command: >
            shopt -s expand_aliases &&
            ./foamStyleCheck/checkStyle

  docs-build:
    docker:
      - image: ubuntu:focal 

    environment:
      WM_NCOMPPROCS: 2
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive

    working_directory: /root/sedfoam
    steps:
      - run:
          name: Install docs packages
          command: >
            apt-get update && apt-get -y install git python3-pip dvisvgm libclang-9-dev &&
            apt-get -y install libclang-cpp9 wget graphviz tex-gyre texlive-base &&
            apt-get -y install texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended
            
      - run:
           name: Add OpenFOAM package repository 
           command: >
             apt-get install -y software-properties-common wget apt-transport-https &&
             sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -" &&
             add-apt-repository http://dl.openfoam.org/ubuntu
             
       - run:
           name: Install OpenFOAM 7 
           command: apt-get update && apt-get -y install openfoam7           
      - run:
          name: Install python packages
          command: >
            shopt -s expand_aliases && python3 --version &&
            pip3 --version &&
            pip3 install -U jinja2 Pygments

      - run:
          name: Make project and user dir
          command: mkdir -p /root/sedfoam

      - checkout:
          path: /root/sedfoam

      - run:
          name: install doxygen 1.8.20
          command: >
            shopt -s expand_aliases &&
            wget http://doxygen.nl/files/doxygen-1.8.20.linux.bin.tar.gz &&
            tar -xvf doxygen-1.8.20.linux.bin.tar.gz

      - run:
          name: clone m.css and build doc
          command: >
            shopt -s expand_aliases &&
            export PATH=$PWD/doxygen-1.8.20/bin:$PATH &&
            cd doc &&
            git clone git://github.com/mosra/m.css &&
            cd m.css/documentation &&
            cp ../../doxygen.py . &&
            source /opt/openfoam7/etc/bashrc &&
            python3 doxygen.py ../../conf.py &&
            cd ../.. && cp images/* mcssout/html/.
      - persist_to_workspace:
          root: /root/sedfoam/doc/mcssout
          paths: html

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "cyrille.bonamy@univ-grenoble-alpes.fr"
            git config user.name "CyrilleBonamy"
      - add_ssh_keys:
          fingerprints:
          - "15:3e:5d:06:c1:98:62:5c:92:99:c5:9f:1e:96:d0:13"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html

  build:
    docker:
      - image: openfoamplus/of_v2006_centos73 

    environment:
      WM_NCOMPPROCS: 2
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive

    working_directory: /root/sedfoam

    steps:
      - run:
          name: Make project and user dir
          command: mkdir -p /root/sedfoam

      - checkout:
          path: /root/sedfoam

      - run:
          name: Build sedFoam
          command: >
            shopt -s expand_aliases &&
            source /opt/OpenFOAM/setImage_v2006.sh &&
            ./Allwmake
      - persist_to_workspace:
          root: /root
          paths: OpenFOAM

  test1:
    docker:
      - image: openfoamplus/of_v2006_centos73 
    working_directory: /root/sedfoam

    steps:
      - run:
          name: Install python3 packages
          command: >
            shopt -s expand_aliases &&
            yum -y install python3 python3-pip && 
            pip3 install fluidfoam

      - checkout:
          path: /root/sedfoam

      - attach_workspace:
          at: /root

      - run:
          name: sedfoam test1D
          command: >
            shopt -s expand_aliases &&
            source /opt/OpenFOAM/setImage_v2006.sh && ls /root/sedfoam &&
            cd test-ci/1DSedim && cp -f constant/forceProperties.sedim constant/forceProperties &&
            cp -f system/controlDict.sedim system/controlDict  && chmod -R a+wX /root &&
            runuser -l ofuser -c 'ln -s /root/OpenFOAM/ . && 
            cd /root/sedfoam/test-ci/1DSedim && ./Allrun' &&
            python3 test_Sedimentation.py
          no_output_timeout: 30m

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkstyle
      - build
      - test1:
          requires:
            - build
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master
